### ISSUE TITLE
Add support for standard-json.

### ISSUE THREAD

**Issue by MicahZoltu** [melonproject/oyente#200]
In a complex project like [Augur](https://github.com/AugurProject/augur-core), the contracts don't compile by just passing them to `solc` because the system is made up of dozens of contracts that have intertwining references and a non-trivial build system.  "Standard JSON" seems to be the recommended mechanism for defining complex builds for solc, so it would be nice if Oyente supported building from a "Standard JSON" file as well so large projects can leverage Oyente (arguably, large projects need Oyente more than small projects).

**Comment by joeykrug** [comment]
Yes please +1

**Comment by luongnt95** [comment]
Thanks @MicahZoltu Will consider it

**Comment by beaugunderson** [comment]
@luongnt95 looks like support was [added here](https://github.com/melonproject/oyente/commit/539a62c5c8a851e4a6380b62124629d4ecd8667d?w=1)--does it work? :)

**Comment by luongnt95** [comment]
@beaugunderson it's not fully supported. Could you help me test this feature?

**Comment by joeykrug** [comment]
Below is a standard JSON output file for solidity, trying it with:

`oyente/oyente.py --standard-json --source contracts.json`

```Traceback (most recent call last):
  File "oyente/oyente.py", line 209, in <module>
    main()
  File "oyente/oyente.py", line 202, in main
    exit_code = analyze_solidity(input_type='standard_json')
  File "oyente/oyente.py", line 105, in analyze_solidity
    helper = InputHelper(InputHelper.STANDARD_JSON, source=args.source, allow_paths=args.allow_paths)
  File "/home/ubuntu/workspace/oyente/input_helper.py", line 44, in __init__
    raise Exception("'%s' attribute can't be None" % attr)
Exception: 'allow_paths' attribute can't be None```

[contracts.json.zip](https://github.com/melonproject/oyente/files/1596356/contracts.json.zip)

It'd be simplest if we could use the solidity json output as then we'd never run into path or build issues w/ oyente.


From above, perhaps it takes the solidity json input instead? I tried that and got the same error though

**Comment by luongnt95** [comment]
@joeykrug Currently, Oyente only gets json input as the input. In order to run json input with Oyente, you have to use --alow-paths parameter as in [solc](https://github.com/ethereum/solidity/issues/2266)
