### ISSUE TITLE
List index out-of-range errors (IndexError) occur in `symExec.check_callstack_attack()`.

### ISSUE THREAD

**Issue by wlzla000** [melonproject/oyente#230]
# `IndexError`

_List index out-of-range_ error (`IndexError`) occurs in:

https://github.com/melonproject/oyente/blob/10386cd0a4a9f702031669de69ba3e1ee931ca8b/oyente/symExec.py#L2148

https://github.com/melonproject/oyente/blob/10386cd0a4a9f702031669de69ba3e1ee931ca8b/oyente/symExec.py#L2152

https://github.com/melonproject/oyente/blob/10386cd0a4a9f702031669de69ba3e1ee931ca8b/oyente/symExec.py#L2154-L2156

-----

# Reason

In `symExec.check_callstack_attack()`,
`disasm[i]` definitely exists, however, `disasm[i + N]` is not ensured to exist;
thus, may cause _list index out-of-range_ errors.

https://github.com/melonproject/oyente/blob/10386cd0a4a9f702031669de69ba3e1ee931ca8b/oyente/symExec.py#L2141-L2164

-----

# To reproduce

##### puzzle_CALL_SWAP4.evm

Note that there's trailing `00F193`<sub>`STOP` `CALL` `SWAP4`</sub>.

```
60606040526004361061006d576000357c0100000000000000000000000000000000000000000000000000000000900463ffffffff168063228cb733146102355780634fb602511461025e578063799320bb146102ec5780638da5cb5b14610319578063a0d7afb71461036e575b341561007857600080fd5b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff163373ffffffffffffffffffffffffffffffffffffffff16141561014c57600060149054906101000a900460ff16156100e757600080fd5b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff166108fc6001549081150290604051600060405180830381858888f193505050505034600181905550610233565b600080369050111561023257600060149054906101000a900460ff161561017257600080fd5b6002546000191660026000366000604051602001526040518083838082843782019150509250505060206040518083038160008661646e5a03f115156101b757600080fd5b505060405180519050600019161015610231573373ffffffffffffffffffffffffffffffffffffffff166108fc6001549081150290604051600060405180830381858888f193505050505060003660039190610214929190610481565b506001600060146101000a81548160ff0219169083151502179055505b5b5b005b341561024057600080fd5b61024861039f565b6040518082815260200191505060405180910390f35b341561026957600080fd5b6102716103a5565b6040518080602001828103825283818151815260200191508051906020019080838360005b838110156102b1578082015181840152602081019050610296565b50505050905090810190601f1680156102de5780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34156102f757600080fd5b6102ff610443565b604051808215151515815260200191505060405180910390f35b341561032457600080fd5b61032c610456565b604051808273ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16815260200191505060405180910390f35b341561037957600080fd5b61038161047b565b60405180826000191660001916815260200191505060405180910390f35b60015481565b60038054600181600116156101000203166002900480601f01602080910402602001604051908101604052809291908181526020018280546001816001161561010002031660029004801561043b5780601f106104105761010080835404028352916020019161043b565b820191906000526020600020905b81548152906001019060200180831161041e57829003601f168201915b505050505081565b600060149054906101000a900460ff1681565b6000809054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b60025481565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106104c257803560ff19168380011785556104f0565b828001600101855582156104f0579182015b828111156104ef5782358255916020019190600101906104d4565b5b5090506104fd9190610501565b5090565b61052391905b8082111561051f576000816000905550600101610507565b5090565b905600F193
```

```
ubuntu64@Ubuntu64:/tmp/lol/oyente/oyente$ ./oyente.py -s ./puzzle_CALL_SWAP4.evm -b
WARNING:root:You are using an untested version of z3. 4.5.0 is the officially tested version
WARNING:root:You are using evm version 1.7.2. The supported version is 1.6.6
WARNING:root:You are using solc version 0.4.18, The latest supported version is 0.4.17
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM Code Coverage: 	 88.4%
Traceback (most recent call last):
  File "./oyente.py", line 320, in <module>
    main()
  File "./oyente.py", line 213, in main
    result = analyze(processed_evm_file, disasm_file)
  File "./oyente.py", line 112, in analyze
    return symExec.main(disasm_file, args.source)
  File "/tmp/lol/oyente/oyente/symExec.py", line 2357, in main
    return detect_vulnerabilies()
  File "/tmp/lol/oyente/oyente/symExec.py", line 2226, in detect_vulnerabilies
    detect_callstack_attack()
  File "/tmp/lol/oyente/oyente/symExec.py", line 2176, in detect_callstack_attack
    pcs = check_callstack_attack(instr)
  File "/tmp/lol/oyente/oyente/symExec.py", line 2152, in check_callstack_attack
    if not disasm[i+j+2][1] == 'POP':
IndexError: list index out of range
INFO:symExec:	====== Analysis Completed ======
ubuntu64@Ubuntu64:/tmp/lol/oyente/oyente$ 
```

**Comment by luongnt95** [comment]
Thanks @wlzla000. The issue is fixed now.
