### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by xuhcc** [melonproject/oyente#237]
Does oyente have python3 support?

I tried to install latest oyente using pip3 from the github repo:

```
pip install -e git+https://github.com/melonproject/oyente#egg=oyente
```

And intstallation was successful, but when I try to analyze contract it gives me the error:

```
$ oyente -a -s contract.sol 
Traceback (most recent call last):
  File "/venv/bin/oyente", line 11, in <module>
    load_entry_point('oyente', 'console_scripts', 'oyente')()
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/venv/src/oyente/oyente/oyente.py", line 11, in <module>
    import symExec
ModuleNotFoundError: No module named 'symExec'
```

**Comment by luongnt95** [comment]
@xuhcc Currently, the version of Oyente having python3 support is not available on pip. To use python3 you must pull Oyente from branch master
