### ISSUE TITLE
Opcode BYTE doesn't work correctly

### ISSUE THREAD

**Issue by luongnt95** [melonproject/oyente#25]
The test case "byte10" in "vmBitwiseLogicOperationTest.json":
[8] PUSH8 0x8040201008040201 
[41] PUSH32 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff 
[42] BYTE 
[44] PUSH1 0x00 
[45] SSTORE
raise exception: ERROR:root:long int too large to convert to int
Traceback (most recent call last):
  File "symExec.py", line 127, in main
    build_cfg_and_analyze()
  File "symExec.py", line 173, in build_cfg_and_analyze
    full_sym_exec()  # jump targets are constructed on the fly
  File "symExec.py", line 452, in full_sym_exec
    return sym_exec_block(0, visited, stack, mem, global_state, path_conditions_and_vars, analysis)
  File "symExec.py", line 476, in sym_exec_block
    sym_exec_ins(start, instr, stack, mem, global_state, path_conditions_and_vars, analysis)
  File "symExec.py", line 1014, in sym_exec_ins
    byte = word & (255 << (8 * (32 - byte_no)))
OverflowError: long int too large to convert to int

Opcode BYTE failed all the tests:
Eg: the test case "byte0":
[8] PUSH8 0x8040201008040201 
[10] PUSH1 0x00 
[12] PUSH1 0x1f 
[13] SUB 
[14] BYTE 
[16] PUSH1 0x00 
[17] SSTORE 

Result is 0: 512
But it should be 0: 1

**Comment by inian** [comment]
@luongnt95 can you check if this has been fixed after https://github.com/melonproject/oyente/pull/26 is merged?

**Comment by luongnt95** [comment]
@inian It was merged but it still raises exception in test case "byte10". I have to check that :)))

**Comment by luongnt95** [comment]
@inian I fixed it

**Comment by inian** [comment]
Ohh I missed that test case..thanks for catching that @luongnt95!
