### ISSUE TITLE
TypeError: cannot use a string pattern on a bytes-like object

### ISSUE THREAD

**Issue by fccbb** [melonproject/oyente#282]
```shell
 % python oyente.py -ce -s TEUICO.sol  :(
WARNING:root:You are using evm version 1.8.2. The supported version is 1.7.3
WARNING:root:You are using solc version 0.4.21, The latest supported version is 0.4.19
Traceback (most recent call last):
  File "oyente.py", line 217, in <module>
    main()
  File "oyente.py", line 212, in main
    exit_code = analyze_solidity()
  File "oyente.py", line 108, in analyze_solidity
    inputs = helper.get_inputs()
  File "/home/blacksheep/Documents/oyente-master/oyente/input_helper.py", line 67, in get_inputs
    contracts = self._get_compiled_contracts()
  File "/home/blacksheep/Documents/oyente-master/oyente/input_helper.py", line 96, in _get_compiled_contracts
    self.compiled_contracts = self._compile_solidity()
  File "/home/blacksheep/Documents/oyente-master/oyente/input_helper.py", line 109, in _compile_solidity
    err = re.sub(self.root_path, "", err)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: cannot use a string pattern on a bytes-like object
```

I tried just to test:

```shell
% oyente                              :(
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 890, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 0.8.1 (/usr/lib/python3.6/site-packages), Requirement.parse('eth-utils==0.7.*'), {'eth-abi'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/oyente", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 683, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 696, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 890, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 0.8.1 (/usr/lib/python3.6/site-packages), Requirement.parse('eth-utils==0.7.*'), {'eth-abi'})
```

that with the latest master branch, I'm not very familiar with python yet any help would be appreciated cheers

**Comment by fccbb** [comment]
well to say that I'm not completely useless I've changed the version of solidity in the .sol file from 0.4.19 to 0.4.21 and it worked. Now every contract that doesn't use my version installed I just edit it :)

**Comment by luongnt95** [comment]
@fccbb Could you pull the master branch again?. I've fixed the issue.

**Comment by fccbb** [comment]
yes it worked now I can use -ru cheers!
