### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by fccbb** [melonproject/oyente#286]
```shell
`% python oyente.py -s s_functionalities.sol
WARNING:root:You are using evm version 1.8.2. The supported version is 1.7.3
WARNING:root:You are using solc version 0.4.21, The latest supported version is 0.4.19
Traceback (most recent call last):
  File "oyente.py", line 220, in <module>
    main()
  File "oyente.py", line 215, in main
    exit_code = analyze_solidity()
  File "oyente.py", line 108, in analyze_solidity
    inputs = helper.get_inputs()
  File "/home/blacksheep/Documents/oyente-master/oyente/input_helper.py", line 74, in get_inputs
    source_map = SourceMap(contract, self.source, 'solidity', self.root_path, self.remap)
  File "/home/blacksheep/Documents/oyente-master/oyente/source_map.py", line 54, in __init__
    self.func_name_to_params = self._get_func_name_to_params()
  File "/home/blacksheep/Documents/oyente-master/oyente/source_map.py", line 122, in _get_func_name_to_params
    func_name_to_params = SourceMap.ast_helper.get_func_name_to_params(self.cname)
  File "/home/blacksheep/Documents/oyente-master/oyente/ast_helper.py", line 151, in get_func_name_to_params
    literal_node = literal_nodes[0]
IndexError: list index out of range
```

so this is with the latest master branch, this time though I didn't find a trick to by pass that yet ;-)

**Comment by luongnt95** [comment]
The bug is fixed now.

**Comment by fccbb** [comment]
working now well done thank you ;-)
