### ISSUE TITLE
ContextualVersionConflict: (eth-utils 0.8.1 Requirement.parse 'eth-utils==0.7.*')

### ISSUE THREAD

**Issue by fccbb** [melonproject/oyente#289]
```python
% oyente -s vicetoken.sol VITTokenSale                              
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 890, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 0.8.1 (/usr/lib/python3.6/site-packages), Requirement.parse('eth-utils==0.7.*'), {'eth-abi'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/oyente", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 683, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 696, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 890, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (eth-utils 0.8.1 (/usr/lib/python3.6/site-packages), Requirement.parse('eth-utils==0.7.*'), {'eth-abi'})

```

??
cheers!

**Comment by luongnt95** [comment]
@fccbb You can try re-installing web3 with python3

**Comment by fccbb** [comment]
no I reinstalled eth-abi ;-)

```python
% sudo pip3 install eth-abi                                                           :(
[sudo] password for blacksheep: 
Requirement already satisfied: eth-abi in /usr/lib/python3.6/site-packages
Collecting eth-utils==0.7.* (from eth-abi)
  Downloading eth_utils-0.7.4-py3-none-any.whl
Requirement already satisfied: cytoolz<1.0.0,>=0.8.2 in /usr/lib/python3.6/site-packages (from eth-utils==0.7.*->eth-abi)
Requirement already satisfied: pysha3<2.0.0,>=1.0.0 in /usr/lib/python3.6/site-packages (from eth-utils==0.7.*->eth-abi)
Requirement already satisfied: toolz>=0.8.0 in /usr/lib/python3.6/site-packages (from cytoolz<1.0.0,>=0.8.2->eth-utils==0.7.*->eth-abi)
Installing collected packages: eth-utils
  Found existing installation: eth-utils 0.8.1
    Uninstalling eth-utils-0.8.1:
      Successfully uninstalled eth-utils-0.8.1
Successfully installed eth-utils-0.7.4
```
