### ISSUE TITLE
how to deal with the version question?

### ISSUE THREAD

**Issue by Messi-Q** [melonproject/oyente#351]
WARNING:root:You are using evm version 1.8.2. The supported version is 1.7.3
WARNING:root:You are using solc version 0.4.21, The latest supported version is 0.4.19
CRITICAL:root:Solidity compilation failed. Please use -ce flag to see the detail.

**Comment by Messi-Q** [comment]
another question
WARNING:root:You are using evm version 1.8.2. The supported version is 1.7.3
WARNING:root:You are using solc version 0.4.21, The latest supported version is 0.4.19
Traceback (most recent call last):
  File "oyente.py", line 221, in <module>
    main()
  File "oyente.py", line 206, in main
    f.write(code)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3068-3069: ordinal not in range(128)

**Comment by molly1214** [comment]
The same problem.

**Comment by yxliang01** [comment]
Please see https://github.com/melonproject/oyente/pull/341
