### ISSUE TITLE
IndexError: pop from empty list

### ISSUE THREAD

**Issue by enderphan94** [melonproject/oyente#372]
when I run the command of `python oyente.py -s contracts/main.sol`, it returns the pop error

```
Traceback (most recent call last):
  File "oyente.py", line 221, in <module>
    main()
  File "oyente.py", line 216, in main
    exit_code = analyze_solidity()
  File "oyente.py", line 109, in analyze_solidity
    results, exit_code = run_solidity_analysis(inputs)
  File "oyente.py", line 86, in run_solidity_analysis
    result, return_code = symExec.run(disasm_file=inp['disasm_file'], source_map=inp['source_map'], source_file=inp['source'])
  File "/oyente/oyente/symExec.py", line 2457, in run
    analyze()
  File "/oyente/oyente/symExec.py", line 2440, in analyze
    run_build_cfg_and_analyze(timeout_cb=timeout_cb)
  File "/oyente/oyente/symExec.py", line 2397, in run_build_cfg_and_analyze
    build_cfg_and_analyze()
  File "/oyente/oyente/symExec.py", line 228, in build_cfg_and_analyze
    full_sym_exec()  # jump targets are constructed on the fly
  File "/oyente/oyente/symExec.py", line 547, in full_sym_exec
    return sym_exec_block(params, 0, 0, 0, -1, 'fallback')
  File "/oyente/oyente/symExec.py", line 612, in sym_exec_block
    sym_exec_ins(params, block, instr, func_call, current_func_name)
  File "/oyente/oyente/symExec.py", line 1857, in sym_exec_ins
    stack.pop(0)
IndexError: pop from empty list
```

**Comment by enderphan94** [comment]
Solve the issue by just moving its file import to the same directory.
